### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by ghost**
I created the Italian translation based on the English badge
Welcome Italy! :-D

### CODE REVIEW

**Comment by albertodonato** [comment]
I wonder if it shouldn't rather be "Scaricala" (referring to the application), or just "Scarica".
AFAIU you're referring to the snap, but a user would really care about downloading an application, not a snap

**Comment by ghost** [comment]
I do not think it's a good idea because all the other badges to always specify the snap store (for example the English one: "Get it from the Snap Store")

**Comment by albertodonato** [comment]
Sorry, my comment wasn't perhaps clear. i meant use "Scarica dallo Snap Store", so just replace "Scaricalo" with "Scarica". Aside from English, all other banners don't seem to mention the object.

**Comment by ghost** [comment]
All right, it seems to me a more than understandable change

**Review by therealjuan-zz — APPROVED** [review]

**Pull request merged**
