### PR TITLE
add Arabic

### PR DESCRIPTION
**Pull request by xlmnxp**
Signed-off-by: Salem Yaslem <s@sy.sa>

### CODE REVIEW

**Comment by xlmnxp** [comment]
@Lukewh will it be accepted?
If there any issue tell me

**Comment by Lukewh** [comment]
@solazio can you take this 😊

**Comment by xlmnxp** [comment]
@solazio the words "احصل عليه من" mean "get it from"

**Comment by solazio** [comment]
@xlmnxp thanks for that. Please bear with us a bit longer and we will get it merged.

**Pull request merged**
