### PR TITLE
Added support of Bengali Language

### PR DESCRIPTION
**Pull request by t4saha**
Added support of Bengali Language

### CODE REVIEW

**Comment by Lukewh** [comment]
Thanks for the contribution :)! Can you pass the SVGs through SVGOMG to remove the Inkscape/ unnecessary metadata please?
There's an online version here: https://jakearchibald.github.io/svgomg/

Thanks

**Comment by t4saha** [comment]
Thank You for valuable observation. I have removed the Inkscape/ unnecessary metadata using https://jakearchibald.github.io/svgomg/

**Comment by Lukewh** [comment]
Hi @t4saha could you update the README.md to resolve the conflict please? Then this is good to land, thanks :)!

**Review by Lukewh — APPROVED** [review]
:+1: Thanks for this!

**Pull request merged**
